name = "TDNEGF"
uuid = "62977e62-62bd-4def-bf7f-9228aeb5e13d"
authors = ["jalil2 "]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
DelimitedFiles = "1.9.1"
DifferentialEquations = "7.17.0"
JLD2 = "0.6.3"
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.16"
Tullio = "0.3.8"
